### ISSUE TITLE
Searched configurations in the main table

### ISSUE THREAD

**Issue by Charleshhy** [ZhangYuanhan-AI/NOAH#10]
Thanks for your nice work!

I just wonder whether it is possible to release the searched configurations (how many prompts/adapter/lora) that are used to reproduce the results for each dataset in table 1 of your paper.

![image](https://user-images.githubusercontent.com/39027479/190940269-63c6f297-52c3-44ce-b136-b51ec633cca5.png)

Thanks in advance!

Kind regards,
Haoyu

**Comment by ZhangYuanhan-AI** [comment]
Thanks for your interest.

Here is the configuration:https://github.com/ZhangYuanhan-AI/NOAH/tree/main/experiments/NOAH/subnet/VTAB
