### ISSUE TITLE
What is the difference between the used ViT-B/16 weights and the weights provided by timm?

### ISSUE THREAD

**Issue by bityangke** [ZhangYuanhan-AI/NOAH#12]
Hi， I found that you used ViT-B/16 weights provided by the google research，not the weights by timm lib.
Could you explain the difference? Thanks!

**Comment by ZhangYuanhan-AI** [comment]
Hi, thanks for your interest.

We use this checkpoint to follow the setting mentioned in the VPT paper. You can check their paper for more details.
