### ISSUE TITLE
error in lib/config.py

### ISSUE THREAD

**Issue by JornyWan** [ZhangYuanhan-AI/NOAH#13]
hi, i followed your instructions and then i met an error shown below:

File "NOAH/lib/config.py", line 36, in update_config_from_file
    exp_config = edict(yaml.safe_load(f))
  File "/.conda/envs/NOAH/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 15: invalid start byte

Then i add " encoding='ISO-8859-1' " to the config.py:

def update_config_from_file(filename):
    exp_config = None
    with open(filename , 'ISO-8859-1') as f:
        exp_config = edict(yaml.safe_load(f))
        _update_config(cfg, exp_config)

but there is a new error making me hard to move to next step:

File "/.conda/envs/NOAH/lib/python3.8/site-packages/yaml/reader.py", line 144, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0003: special characters are not allowed
  in "vit_model/ViT-B_16.npz", position 2

could you please solve this problem? and if there are any other problems that you did not post? i just want to reproduce this work. thx!

**Comment by ZhangYuanhan-AI** [comment]
Hi Jorny,

Thank you for expressing your interest. Kindly provide information regarding the environments in which you have executed this code.

**Comment by JornyWan** [comment]
thx, i just fixed them all!
