### ISSUE TITLE
Question about Adapter

### ISSUE THREAD

**Issue by RaptorMai** [ZhangYuanhan-AI/NOAH#14]
Thank you so much for sharing the code. In the original paper of the Adapter, one Adapter layer is placed after the Attention module and the other one is placed after the FF layer. In your paper, it seems the Adapter layer is only placed after the FF layer. Could you elaborate on the rationale behind this change? Thank you so much in advance, and I look forward to hearing back from you.

**Comment by ZhangYuanhan-AI** [comment]
Hi Mai,

We follow the setting mentioned in the VPT paper: https://arxiv.org/pdf/2203.12119.pdf page 15.

As it said:  [63,64] exhaustively searched all possible configurations and found that only inserting adapters after the FFN “Add & LayerNorm”sub-layer works the best. Therefore we also use this setup in our own implementation.

**Comment by RaptorMai** [comment]
Thanks for your answer. I have one more question. In the adapter module, the forward already includes x (the residual). In the Block module of ViT, the forward adds another residual x after the adapter, `x = x + self.adapter(self.drop_path(self.mlp(self.norm2(x))))`. This will make the final output have two x, right?

    def forward(self, x, identity=None):
        if self.identity:
            # import pdb;pdb.set_trace()
            return x
            # return x + 0*self.sampled_weight_0 + 0*self.sampled_bias_0 + 0*self.sampled_weight_1 + 0*self.sampled_bias_1
        # import pdb;pdb.set_trace()
        out = F.linear(x, self.sampled_weight_0, self.sampled_bias_0)
        out = self.activate(out)
        out = self.dropout(out)
        out = F.linear(out, self.sampled_weight_1, self.sampled_bias_1)
        if identity is None:
            identity = x
        return identity + out
