### ISSUE TITLE
Questions about reproduction.

### ISSUE THREAD

**Issue by MouxiaoHuang** [ZhangYuanhan-AI/NOAH#15]
Great job on your work, and thank you for sharing the code. I do have a few questions regarding running the experiments on vtab-1k.

Regarding VPT / Adapter / LoRA:

- Acc performance: My results for Adapter and LoRA are significantly worse than the original paper (72.0 / 73.9 / 74.5), with my results being 72.81 / 71.65 / 72.35, respectively. I used your configuration files and scripts directly to run Adapter and LoRA, but I am not sure if the code is the exact version used to produce the results in the original paper.
- Params: The prompt length of VPT varies across different datasets. How do you determine the parameters for VPT to be 0.64M?

Regarding NOAH:

- The pipeline has three stages: 1) supernet training; 2) evolutionary search; 3) subnet retraining. In evolutionary search, should the parameter `LIMITS` be 0.64? However, it seems to make the searching process omit a lot of subnets (I'm not sure if this is correct)? The original paper says `Output: a new subset C and its performance on val set: {C:Acc.}`, but my searching logs cannot produce such results. For instance, `*-caltech101-vtab-search.log` shows the `Acc@1` is only 1.000, which is very low and random.
- Additionally, how can I obtain the subnet configuration files in `experiments/NOAH/subnet/VTAB`?

Regarding others:

- The model config includes visual_prompt, lora, adapter, and prefix. What does prefix mean here? Is it another method different from VPT / Adapter / LoRA?

I look forward to your response.

**Comment by ZhangYuanhan-AI** [comment]
Hi Mouxiao

Could you please kindly provide me with the training log of your experiments?

**Comment by MouxiaoHuang** [comment]
Thank you for getting back to me promptly.

Certainly. As an illustration, I have provided the training logs for Caltech101, which involve VPT, Adapter, LoRA, Supernet, and the corresponding searching log for Supernet, via the following link: [link](https://drive.google.com/drive/folders/1GyiKNjNjQKlC-gBhSNGEde8jMRpiGw1O?usp=sharing).

**Comment by ZhangYuanhan-AI** [comment]
Regarding VPT / Adapter / LoRA:

1. I conducted evaluations for each configuration using three distinct random seeds, subsequently reporting the mean performance. It is recommended to replicate this process. In the event of persisting issues, we can further analysis.

Regarding NOAH:
1. Indeed, one potential limitation of NOAH lies in its efficiency during the search phase, particularly when faced with small "LIMITS" values. Exploring ways to enhance efficiency under these conditions may prove to be a fruitful direction for improving NOAH. Notably, some solutions have been proposed within the context of Neural Architecture Search (NAS). 
2.  It is imperative to verify the accurate loading of the supernet.

Regarding others:
1. Yes, it is the prefix-tuning method. I found this method perform similarly to VPT, so I do not report this performance.

**Comment by MouxiaoHuang** [comment]
Thank you for your response, which helped me clarify most of the questions I had.

In addition, I am still confused about the results of evolutionary search experiments. Would it be possible for you to provide a sample search log for any one of the vtab-1k sub-datasets?

**Comment by ZhangYuanhan-AI** [comment]
Sure.  
Check this:https://drive.google.com/file/d/1lW980rK9QIjOidCzdzzs_3s6cPevh1Ey/view?usp=sharing
The log for this configure:https://github.com/ZhangYuanhan-AI/NOAH/blob/main/experiments/NOAH/subnet/few-shot/ViT-B_prompt_oxford_pets_shot16-seed0.yaml

**Comment by MouxiaoHuang** [comment]
Oh, I figured out why my accuracy results from the search algorithm were confusing and nearly random. It turns out that the issue was caused by the difference in the timm.load_checkpoint function between version 0.4 and versions 0.5 or higher.

Thanks again for your prompt and helpful response.
