### ISSUE TITLE
Regarding data pipeline of ImageNet

### ISSUE THREAD

**Issue by Arnav0400** [ZhangYuanhan-AI/NOAH#17]
Hello Authors,

I was trying to run ImageNet 16-shot experiment and couldn't find the annotation file for ImageNet https://github.com/ZhangYuanhan-AI/NOAH/blob/c868cc7c2273ca79c4df35dc5e54cd10638dd04f/lib/datasets.py#L56 Can you please let me know how to run the ImageNet experiment.

**Comment by ZhangYuanhan-AI** [comment]
Have you followed https://github.com/KaiyangZhou/CoOp/blob/main/DATASETS.md ?

**Comment by Arnav0400** [comment]
Yes, I already have the imagenet folder in place

**Comment by ZhangYuanhan-AI** [comment]
here: https://github.com/ZhangYuanhan-AI/NOAH/tree/main/data/few-shot/imagenet/annotations
