### ISSUE TITLE
Problem preparing RESISC45 and Diabetic Retinopathy dataset

### ISSUE THREAD

**Issue by minhlong94** [ZhangYuanhan-AI/NOAH#18]
Hi authors,

Thank you for your work. I am using your code repo for my project. I am trying to prepare the RESISC45 and Diabetic Retinopathy dataset using the script `python get_vtab1k.py`. I manually downloaded these datasets and successfully prepared them. However, when I run the script, it throws me `FileNotFoundError: [Errno 2] No such file or directory: './data/vtab-1k/resisc45/train800val200.txt'`. I check the folder and there is no `txt` file created. 

The issue happens to Diabetic as well. Can you help me with what I am missing?

**Comment by ZhangYuanhan-AI** [comment]
uploaded: https://drive.google.com/file/d/1abt7LW1rUMZfHukC5PDA9lhQ_LFX8WTj/view?usp=sharing

**Comment by minhlong94** [comment]
Thank you for the file! Can you provide the file for Diabetic dataset as well?

**Comment by ZhangYuanhan-AI** [comment]
> Thank you for the file! Can you provide the file for Diabetic dataset as well?

uploaded.

**Comment by Allencheng97** [comment]
@minhlong94 Could you please give more details on how to manually prepare RESISC45? The given one drive link is  rar file. I tried to extract the rar into a folder, tar the extracted folder, put the original rar file into data/vtab/resisc45/manual, but still got the error information.
![image](https://github.com/ZhangYuanhan-AI/NOAH/assets/47037416/2fdbb623-9855-4e60-a81b-ed141c7bde50)
