### ISSUE TITLE
One question about experiments on domain generalization.

### ISSUE THREAD

**Issue by tfwang96** [ZhangYuanhan-AI/NOAH#9]
Is the model trained on Imagenet (16 shots per category) from scrath?

**Comment by ZhangYuanhan-AI** [comment]
No. From [ViT B-16](https://storage.googleapis.com/vit_models/imagenet21k/ViT-B_16.npz)

**Comment by tfwang96** [comment]
> No. From [ViT B-16](https://storage.googleapis.com/vit_models/imagenet21k/ViT-B_16.npz)

Is this model pretrained on imagenet?

**Comment by tfwang96** [comment]
> No. From [ViT B-16](https://storage.googleapis.com/vit_models/imagenet21k/ViT-B_16.npz)

Thanks for your reply, I've got it.

**Comment by ZhangYuanhan-AI** [comment]
> > No. From [ViT B-16](https://storage.googleapis.com/vit_models/imagenet21k/ViT-B_16.npz)
> 
> Thanks for your reply, I've got it.

👍👍👍
